[metadata]
name = "timethese"
version = "0.0.7"
description = ""
authors = ["Joachim Bargsten <jw@bargsten.org>"]
license = "MIT"

[build-system]
requires = ["setuptools", "wheel"]
# build-backend = "setuptools.build-meta"

[tool.black]
line-length = 110
target-version = ['py35']
